"""Core Smuggler constants."""

from __future__ import annotations


GOODS_COUNT = 6
DISTRICT_COUNT = 6
TRADER_SLOTS = 4
SCORE_ROWS = 5
EVENT_MSG_MAX = 12
TRIUMPH_TARGET = 10000

ACTION_NONE = 0
ACTION_BUY = 1
ACTION_SELL = 2
ACTION_TRAVEL = 3
ACTION_VAULT = 4
ACTION_LENDER = 5
ACTION_CACHE = 6
ACTION_QUIT = 7
ACTION_SCORES = 8
ACTION_REDRAW = 9
ACTION_SELLSWORDS = 10
ACTION_CARTWRIGHT = 11

EVENT_CLASS_INFO = "info"
EVENT_CLASS_GAIN = "gain"
EVENT_CLASS_WARNING = "warning"
EVENT_CLASS_DANGER = "danger"
EVENT_CLASS_THEFT = "theft"

SWORD_NONE = 0
SWORD_KNIFE = 1
SWORD_GLADIUS = 2
SWORD_SPATHA = 3

ARMOR_NONE = 0
ARMOR_LEATHER = 1
ARMOR_MAIL = 2
ARMOR_SCALE = 3

SCORE_FILE = "smuggle_scores.json"
SAVE_PREFIX = "smuggle_state_"
