name = "Games and Utils"
title = "Games and Utils (%t mins)"
header_file = ""
header_types = ["Novice", "Regular", "Expert"]
menu_file = ""
menu_types = []
menu_length = 0
menu_color = -1
option_width = 0

[[option]]
command = "MEX"
arguments = "scripts/card"
priv_level = "Demoted"
description = "b mex blackjack"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/weather"
priv_level = "Demoted"
description = "w weather forecast"
key_poke = ""
modifiers = []

[[option]]
command = "Goodbye"
arguments = ""
priv_level = "Demoted"
description = "Goodbye"
key_poke = ""
modifiers = []

[[option]]
command = "Display_Menu"
arguments = "MAIN"
priv_level = "Demoted"
description = "q quit to main"
key_poke = ""
modifiers = []
